import requests
import matplotlib.pyplot as plt
from fpdf import FPDF
from datetime import datetime
import os
import random

FIREBASE_URL = "https://aquasmart-system-default-rtdb.firebaseio.com"
PONDS_TO_REPORT = ["pond_1", "pond_2", "pond_3"] 
HOURS_SIM = [f"{i:02d}:00" for i in range(0, 24, 2)]

def clean_text(text):
    if not isinstance(text, str): return str(text)
    return text.encode('latin-1', 'ignore').decode('latin-1').strip()

def get_archive_path():
    today = datetime.now().strftime("%Y-%m-%d")
    path = os.path.join("Reports_Archive", today)
    if not os.path.exists(path):
        os.makedirs(path)
    return path

def generate_fake_data(pond_name):
    print(f"⚠️ Simulation Mode: {pond_name}")
    temp = [round(random.uniform(25.0, 27.0), 1) for _ in range(12)]
    ph = [round(random.uniform(7.2, 7.6), 1) for _ in range(12)]
    do_val = [round(random.uniform(6.5, 8.0), 1) for _ in range(12)]
    ammonia = [round(random.uniform(0.0, 0.1), 2) for _ in range(12)]
    
    if pond_name == "pond_2": 
        ammonia[8] = 1.4; do_val[8] = 3.2
    
    statuses = []
    for i in range(12):
        if ammonia[i] > 0.8 or do_val[i] < 4.2: statuses.append("Danger")
        elif ammonia[i] > 0.5: statuses.append("Warning")
        else: statuses.append("Safe")
        
    return HOURS_SIM, temp, ph, do_val, ammonia, statuses

def fetch_real_data(pond_id):
    print(f"📡 Fetching Firebase: {pond_id}")
    url = f"{FIREBASE_URL}/ponds/{pond_id}/history/readings.json"
    try:
        response = requests.get(url, timeout=5)
        data = response.json()
        if not data: return None
        
        readings = []
        for key, val in data.items():
            if isinstance(val, dict) and 'time' in val: readings.append(val)
        
        if len(readings) < 3: return None 

        readings.sort(key=lambda x: x['time'])
        latest = readings[-12:] 
        
        times = [r['time'].split(' ')[1][:5] for r in latest]
        temps = [float(r.get('T', 0)) for r in latest]
        phs = [float(r.get('pH', 0)) for r in latest]
        dos = [float(r.get('DO', 0)) for r in latest]
        nh3s = [float(r.get('NH3', 0)) for r in latest]
        statuses = [r.get('status', 'Unknown') for r in latest]
        
        return times, temps, phs, dos, nh3s, statuses
    except:
        return None

class PDF(FPDF):
    def header(self):
        if os.path.exists('logo.png'): 
            self.image('logo.png', 10, 10, 40)
        
        self.set_font('Arial', 'B', 22)
        self.set_text_color(44, 62, 80)
        self.cell(0, 15, 'AquaSmart AI System', 0, 1, 'C')
        
        self.set_font('Arial', '', 11)
        self.set_text_color(127, 140, 141)
        self.cell(0, 5, 'Comprehensive Water Quality Analysis Report', 0, 1, 'C')
        
        self.ln(15)
        self.set_draw_color(44, 62, 80)
        self.line(10, 45, 200, 45)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by AquaSmart AI', 0, 0, 'C')

def create_smart_report(pond_id):
    data = fetch_real_data(pond_id)
    is_real = True
    if not data:
        data = generate_fake_data(pond_id)
        is_real = False
    
    times, temps, phs, dos, nh3s, statuses = data
    pond_title = pond_id.replace("_", " ").title()

    chart_files = []
    def draw_chart(filename, x, y, title, color, limit=None):
        plt.figure(figsize=(10, 3.5))
        plt.plot(x, y, marker='o', color=color, linewidth=2)
        if limit: plt.axhline(y=limit, color='red', linestyle='--', label='Limit')
        plt.title(title, fontweight='bold')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(filename)
        plt.close()
        return filename

    chart_files.append(draw_chart('c1.png', times, temps, f'Temperature ({pond_title})', '#e67e22'))
    chart_files.append(draw_chart('c2.png', times, phs, f'pH Level ({pond_title})', '#8e44ad'))
    chart_files.append(draw_chart('c3.png', times, nh3s, f'Ammonia ({pond_title})', '#c0392b', 0.8))
    chart_files.append(draw_chart('c4.png', times, dos, f'Dissolved Oxygen ({pond_title})', '#2980b9', 4.2))

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(0)
    src = "(LIVE SENSOR DATA)" if is_real else "(SIMULATED DATA)"
    pdf.cell(0, 8, f'Target: {pond_title}   |   Date: {datetime.now().strftime("%Y-%m-%d")}', 0, 1)
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(100)
    pdf.cell(0, 6, f'Data Source: {src}', 0, 1)
    pdf.ln(5)

    pdf.set_fill_color(236, 240, 241)
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, '  1. AI Executive Summary', 0, 1, 'L', 1)
    pdf.ln(3)

    full_status = " ".join([str(s) for s in statuses])
    if "Danger" in full_status:
        msg = "CRITICAL: The system detected unsafe conditions. High Ammonia or Low Oxygen levels were recorded. Immediate corrective action (Aeration/Water Exchange) is recommended."
    elif "Warning" in full_status:
        msg = "WARNING: System stability is fluctuating. Some parameters are approaching unsafe limits. Increase monitoring frequency."
    else:
        msg = "OPTIMAL: All water quality parameters are within safe ranges. The ecosystem is stable and healthy."
    
    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(0)
    pdf.multi_cell(0, 6, clean_text(msg))
    pdf.ln(8)

    pdf.set_fill_color(236, 240, 241)
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, '  2. Key Statistics', 0, 1, 'L', 1)
    pdf.ln(3)

    def draw_stat_row(lbl, v, unit):
        avg = sum(v)/len(v)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(50, 8, lbl, 1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(45, 8, f"Min: {min(v):.1f} {unit}", 1, 0, 'C')
        pdf.cell(45, 8, f"Max: {max(v):.1f} {unit}", 1, 0, 'C')
        pdf.cell(45, 8, f"Avg: {avg:.1f} {unit}", 1, 1, 'C')

    draw_stat_row("Temperature", temps, "C")
    draw_stat_row("Acidity (pH)", phs, "")
    draw_stat_row("Ammonia (NH3)", nh3s, "mg/L")
    draw_stat_row("Oxygen (DO)", dos, "mg/L")
    pdf.ln(10)

    pdf.set_fill_color(236, 240, 241)
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, '  3. Visual Trends Analysis', 0, 1, 'L', 1)
    pdf.ln(5)

    for c_file in chart_files:
        if os.path.exists(c_file):
            if pdf.get_y() > 220: pdf.add_page()
            pdf.image(c_file, x=10, w=190)
            pdf.ln(2)

    pdf.add_page()
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '  4. Detailed Hourly Logs', 0, 1, 'L', 1)
    pdf.ln(5)

    pdf.set_fill_color(44, 62, 80)
    pdf.set_text_color(255)
    pdf.set_font('Arial', 'B', 9)
    cols = [25, 25, 25, 25, 25, 35]
    headers = ['Time', 'Temp', 'pH', 'NH3', 'DO', 'AI Status']
    for i, h in enumerate(headers): pdf.cell(cols[i], 8, h, 1, 0, 'C', 1)
    pdf.ln()

    pdf.set_text_color(0)
    pdf.set_font('Arial', '', 9)
    for i in range(len(times)):
        raw_status = str(statuses[i])
        fill = False
        pdf.set_fill_color(255, 255, 255)
        if "Danger" in raw_status:
            pdf.set_fill_color(231, 76, 60); fill = True
            pdf.set_text_color(255)
        elif "Warning" in raw_status:
            pdf.set_fill_color(241, 196, 15); fill = True
            pdf.set_text_color(0)
        else:
            pdf.set_text_color(0)

        pdf.cell(cols[0], 7, str(times[i]), 1, 0, 'C', fill)
        pdf.cell(cols[1], 7, str(temps[i]), 1, 0, 'C', fill)
        pdf.cell(cols[2], 7, str(phs[i]), 1, 0, 'C', fill)
        pdf.cell(cols[3], 7, str(nh3s[i]), 1, 0, 'C', fill)
        pdf.cell(cols[4], 7, str(dos[i]), 1, 0, 'C', fill)
        pdf.cell(cols[5], 7, clean_text(raw_status)[:15], 1, 1, 'C', fill)

    archive_dir = get_archive_path()
    current_time = datetime.now().strftime("%H-%M-%S")
    out_name = f"{archive_dir}/Report_{pond_id}_{current_time}.pdf"
    
    pdf.output(out_name)
    print(f"✅ Archived: {out_name}")
    
    for c in chart_files: 
        if os.path.exists(c): os.remove(c)

if __name__ == "__main__":
    print(f"🚀 Archiving Reports at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}...")
    for pond in PONDS_TO_REPORT:
        create_smart_report(pond)
    print("\n🎉 Mission Complete! Check 'Reports_Archive' folder.")